name = "DynamicsPlots"
uuid = "2f97d39f-9754-482a-91aa-b40596fbfbc8"
authors = ["rmsmsgood <rmsmsgood@naver.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Plots = "0.28, 0.29, 1.0"
julia = "1"