name = "DynamicsPlots"
uuid = "2f97d39f-9754-482a-91aa-b40596fbfbc8"
authors = ["rmsmsgood <rmsmsgood@naver.com>"]
version = "0.1.3"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
DataFrames = "1"
Plots = "1"
RecipesBase = "1"
julia = "1"